# GitHub Sponsors funding options
github: [HighervGround]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# custom: ["https://example.com"]